# Generated by Django 4.0 on 2022-05-04 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('movies', '0002_rating_movie_owner_delete_favorites_rating_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='account.customuser'),
        ),
    ]
